"use client";

import { useState, useEffect, Suspense } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api/client";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { SlideUp } from "@/components/ui/motion-wrapper";
import { IdeaCard } from "@/components/explore/IdeaCard";
import { Search, SlidersHorizontal } from "lucide-react";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";

interface ExploreIdea {
  _id: string;
  projectTitle: string;
  elevatorPitch?: string;
  techStack: string[];
  createdAt: string;
}

function ExploreContent() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const initialSearch = searchParams.get("q") || "";
  const sort = searchParams.get("sort") || "newest";
  const pageParam = searchParams.get("page");
  const currentPage = pageParam ? parseInt(pageParam, 10) : 1;

  const [search, setSearch] = useState(initialSearch);

  const createPageURL = (pageNumber: number | string) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("page", pageNumber.toString());
    return `${pathname}?${params.toString()}`;
  };

  // Debounce search input to update URL params
  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      const params = new URLSearchParams(searchParams.toString());
      let changed = false;

      if (search) {
        if (params.get("q") !== search) {
          params.set("q", search);
          params.set("page", "1");
          changed = true;
        }
      } else {
        if (params.has("q")) {
          params.delete("q");
          params.set("page", "1");
          changed = true;
        }
      }

      if (changed) {
        router.push(`${pathname}?${params.toString()}`, { scroll: false });
      }
    }, 300);

    return () => clearTimeout(delayDebounceFn);
  }, [search, pathname, router, searchParams]);

  const handleSortChange = (newSort: string) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("sort", newSort);
    params.set("page", "1");
    router.push(`${pathname}?${params.toString()}`, { scroll: false });
  };

  const { data, isPending } = useQuery({
    queryKey: ["explore", searchParams.get("q"), sort, currentPage],
    queryFn: () => {
      const params = new URLSearchParams();
      const currentQ = searchParams.get("q");
      if (currentQ) params.set("q", currentQ);

      params.set("sort", sort);
      params.set("page", currentPage.toString());
      params.set("limit", "9");
      return apiClient<{
        ideas: ExploreIdea[];
        pagination: Record<string, number>;
      }>(`/api/ideas?${params.toString()}`);
    },
  });

  const ideas = data?.ideas || [];
  const pagination = data?.pagination;

  return (
    <div className="min-h-[60vh] py-12 bg-background">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <SlideUp>
          <div className="text-center mb-10">
            <h1 className="text-4xl font-extrabold tracking-tight font-heading text-foreground">
              Explore Products
            </h1>
            <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
              Browse innovative product ideas and business plans generated by
              the community. Find inspiration for your next big launch.
            </p>
          </div>
        </SlideUp>

        <SlideUp delay={0.1}>
          <div className="flex flex-col sm:flex-row gap-4 mb-8 items-center justify-between">
            <div className="relative w-full sm:max-w-md">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
              <Input
                placeholder="Search products, niches, or tech stacks..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>

            <div className="w-full sm:w-auto overflow-x-auto">
              <Tabs value={sort} onValueChange={handleSortChange}>
                <TabsList className="w-full sm:w-auto">
                  <TabsTrigger value="newest">Newest</TabsTrigger>
                  <TabsTrigger value="oldest">Oldest</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
          </div>
        </SlideUp>

        {isPending ? (
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {Array.from({ length: 8 }).map((_, i) => (
              <Card key={i} className="h-full">
                <CardContent className="p-5">
                  <div className="h-6 w-3/4 bg-muted rounded animate-pulse mb-3 mt-2" />
                  <div className="h-4 w-1/4 bg-muted rounded animate-pulse mb-4" />
                  <div className="h-4 w-full bg-muted rounded animate-pulse mb-2" />
                  <div className="h-4 w-5/6 bg-muted rounded animate-pulse mb-4" />
                  <div className="flex gap-2 mt-auto pt-4">
                    <div className="h-6 w-16 bg-muted rounded animate-pulse" />
                    <div className="h-6 w-16 bg-muted rounded animate-pulse" />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : ideas.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center bg-muted/30 rounded-lg border border-dashed mt-8">
            <SlidersHorizontal className="size-12 text-muted-foreground/30 mb-4" />
            <h3 className="text-lg font-semibold">No product ideas found</h3>
            <p className="text-sm text-muted-foreground mt-1">
              Try adjusting your search terms or filters.
            </p>
          </div>
        ) : (
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {ideas.map((idea, i) => (
              <SlideUp
                key={idea._id}
                delay={Math.min(i * 0.05, 0.5)}
                className="h-full"
              >
                <IdeaCard {...idea} />
              </SlideUp>
            ))}
          </div>
        )}

        {!isPending && ideas.length > 0 && pagination && pagination.pages > 1 && (
          <div className="mt-12 flex justify-center">
            <Pagination>
              <PaginationContent>
                <PaginationItem>
                  <PaginationPrevious 
                    href={currentPage > 1 ? createPageURL(currentPage - 1) : "#"} 
                    className={currentPage <= 1 ? "pointer-events-none opacity-50" : ""}
                  />
                </PaginationItem>
                
                {[...Array(pagination.pages)].map((_, i) => {
                  const page = i + 1;
                  if (
                    page === 1 || 
                    page === pagination.pages || 
                    (page >= currentPage - 1 && page <= currentPage + 1)
                  ) {
                    return (
                      <PaginationItem key={page}>
                        <PaginationLink 
                          href={createPageURL(page)}
                          isActive={page === currentPage}
                        >
                          {page}
                        </PaginationLink>
                      </PaginationItem>
                    );
                  }
                  
                  if (page === currentPage - 2 || page === currentPage + 2) {
                    return (
                      <PaginationItem key={`ellipsis-${page}`}>
                        <PaginationEllipsis />
                      </PaginationItem>
                    );
                  }
                  
                  return null;
                })}

                <PaginationItem>
                  <PaginationNext 
                    href={currentPage < pagination.pages ? createPageURL(currentPage + 1) : "#"} 
                    className={currentPage >= pagination.pages ? "pointer-events-none opacity-50" : ""}
                  />
                </PaginationItem>
              </PaginationContent>
            </Pagination>
          </div>
        )}
      </div>
    </div>
  );
}

export default function ExplorePage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-[60vh] flex items-center justify-center">
          <Search className="size-6 animate-pulse text-muted-foreground" />
        </div>
      }
    >
      <ExploreContent />
    </Suspense>
  );
}
