"use client";

import { use, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api/client";
import { getToken } from "@/lib/api/get-token";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SlideUp } from "@/components/ui/motion-wrapper";
import Link from "next/link";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import {
  Loader2,
  ArrowLeft,
  Clock,
  Copy,
  Check,
  Globe,
  Lock,
  FileText,
  Target,
  Users,
  Settings,
  Layout,
  AlertTriangle,
  Book
} from "lucide-react";
import { toast } from "sonner";

interface Idea {
  _id: string;
  projectTitle: string;
  tagline: string;
  techStack: string[];
  elevatorPitch: string;
  estimatedDuration: string;
  ownerName: string;
  createdAt: string;
  visibility?: string;
  prdSections?: {
    executiveSummary: string;
    strategyAndContext: string;
    usersAndScope: string;
    requirementsAndLogic: string;
    designAndExecution: string;
    planningAndRisk: string;
    appendix: string;
  };
}

export default function IdeaDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);

  const { data, isPending, error } = useQuery({
    queryKey: ["project idea", id],
    queryFn: async () => {
      const token = await getToken();
      return apiClient<{ idea: Idea; related: Idea[] }>(
        `/api/ideas/${id}`,
        { token }
      );
    },
  });

  const [copied, setCopied] = useState(false);

  if (isPending) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <Loader2 className="size-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error || !data?.idea) {
    notFound();
  }

  const { idea, related } = data;

  const handleCopy = async () => {
    try {
      const sections = idea.prdSections ? [
        idea.prdSections.executiveSummary,
        idea.prdSections.strategyAndContext,
        idea.prdSections.usersAndScope,
        idea.prdSections.requirementsAndLogic,
        idea.prdSections.designAndExecution,
        idea.prdSections.planningAndRisk,
        idea.prdSections.appendix
      ] : [];
      await navigator.clipboard.writeText(sections.filter(Boolean).join("\\n\\n---\\n\\n"));
      setCopied(true);
      toast.success("Idea copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy idea");
    }
  };

  return (
    <div className="min-h-[60vh] py-12 bg-muted/20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SlideUp>
          <div className="flex items-center justify-between mb-6">
            <Link
              href="/explore/ideas"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="size-4" /> Back to Explore
            </Link>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="gap-2"
            >
              {copied ? <Check className="size-4" /> : <Copy className="size-4" />}
              {copied ? "Copied" : "Copy Idea"}
            </Button>
          </div>
        </SlideUp>

        <SlideUp delay={0.05}>
          <div className="mb-6">
            <h1 className="font-heading scroll-m-20 text-3xl font-bold tracking-tight lg:text-4xl mb-2">
              {idea.projectTitle}
            </h1>
            <p className="text-lg text-muted-foreground font-medium mb-4">
              {idea.tagline}
            </p>
            
            <div className="flex flex-wrap items-center gap-2 mt-4">
              <Badge variant="secondary" className="px-3 py-1 text-xs font-medium">
                <Clock className="size-3 mr-1.5" /> Can be built in {idea.estimatedDuration}
              </Badge>
              <Badge variant="outline" className="px-3 py-1 text-xs font-medium">
                Generated by {idea.ownerName}
              </Badge>
              {idea.visibility === "private" ? (
                <Badge variant="outline" className="px-3 py-1 text-xs font-medium border-amber-500/40 text-amber-600 dark:text-amber-400">
                  <Lock className="size-3 mr-1.5" /> Private
                </Badge>
              ) : (
                <Badge variant="outline" className="px-3 py-1 text-xs font-medium text-muted-foreground">
                  <Globe className="size-3 mr-1.5" /> Public
                </Badge>
              )}
            </div>
          </div>
        </SlideUp>

        <Separator className="my-6" />

        <Tabs defaultValue="overview" className="w-full">
          <SlideUp delay={0.1}>
            <div className="w-full mb-6 overflow-x-auto pb-2 scrollbar-hide">
              <TabsList className="inline-flex h-auto w-auto min-w-full sm:min-w-0 justify-start bg-muted/50 p-1">
                <TabsTrigger value="overview" className="text-sm whitespace-nowrap px-4 py-2">Strategy & Context</TabsTrigger>
                <TabsTrigger value="architecture" className="text-sm whitespace-nowrap px-4 py-2">Requirements & Logic</TabsTrigger>
                <TabsTrigger value="execution" className="text-sm whitespace-nowrap px-4 py-2">Planning & Execution</TabsTrigger>
              </TabsList>
            </div>
          </SlideUp>

          <TabsContent value="overview" className="space-y-4 focus-visible:outline-none focus-visible:ring-0">
            <SlideUp delay={0.1}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <FileText className="size-5" /> Executive Summary
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.executiveSummary || "Generating Executive Summary..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>

            <SlideUp delay={0.2}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <Target className="size-5" /> Strategy & Context
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.strategyAndContext || "Generating Strategy & Context..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>

            <SlideUp delay={0.3}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <Users className="size-5" /> Users & Scope
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.usersAndScope || "Generating Users & Scope..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>
          </TabsContent>

          <TabsContent value="architecture" className="space-y-4 focus-visible:outline-none focus-visible:ring-0">
            <SlideUp delay={0.1}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <Settings className="size-5" /> Requirements & Logic
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.requirementsAndLogic || "Generating Requirements & Logic..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>

            <SlideUp delay={0.2}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <Layout className="size-5" /> Design & Execution
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.designAndExecution || "Generating Design & Execution..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>
          </TabsContent>

          <TabsContent value="execution" className="space-y-4 focus-visible:outline-none focus-visible:ring-0">
            <SlideUp delay={0.1}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <AlertTriangle className="size-5" /> Planning & Risk Management
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.planningAndRisk || "Generating Planning & Risk Management..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>

            <SlideUp delay={0.2}>
              <Card className="border bg-card shadow-sm">
                <CardHeader className="pb-4 border-b">
                  <CardTitle className="text-xl font-heading font-bold tracking-tight flex items-center gap-2.5 text-amber-600 dark:text-amber-500">
                    <Book className="size-5" /> Appendix / Glossary
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0 sm:p-10 sm:pt-0">
                  <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-heading prose-headings:font-bold prose-headings:tracking-tight prose-a:text-primary">
                    <ReactMarkdown>{idea.prdSections?.appendix || "Generating Appendix..."}</ReactMarkdown>
                  </div>
                </CardContent>
              </Card>
            </SlideUp>
          </TabsContent>
        </Tabs>

        {related?.length > 0 && (
          <SlideUp delay={0.35}>
            <div className="mt-12">
              <h2 className="font-heading text-xl font-bold tracking-tight mb-4">
                Related Ideas
              </h2>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {related.map((r) => (
                  <Link key={r._id} href={`/explore/ideas/${r._id}`}>
                    <Card className="h-full hover:shadow-md transition-shadow">
                      <CardContent className="p-5">
                        <h3 className="font-semibold line-clamp-1 mb-1">{r.projectTitle}</h3>
                        <p className="text-sm text-muted-foreground line-clamp-2">{r.elevatorPitch}</p>
                        <div className="flex flex-wrap gap-1 mt-2">
                          {r.techStack?.slice(0, 3).map((t) => (
                            <Badge
                              key={t}
                              variant="outline"
                              className="text-xs"
                            >
                              {t}
                            </Badge>
                          ))}
                        </div>
                      </CardContent>
                    </Card>
                  </Link>
                ))}
              </div>
            </div>
          </SlideUp>
        )}
      </div>
    </div>
  );
}
