"use client";

import { use, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api/client";
import { getToken } from "@/lib/api/get-token";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SlideUp } from "@/components/ui/motion-wrapper";
import Link from "next/link";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import { Separator } from "@/components/ui/separator";
import {
  Loader2,
  ArrowLeft,
  Clock,
  Copy,
  Check,
  Globe,
  Lock
} from "lucide-react";
import { toast } from "sonner";

interface Idea {
  _id: string;
  projectTitle: string;
  tagline: string;
  techStack: string[];
  elevatorPitch: string;
  estimatedDuration: string;
  ownerName: string;
  createdAt: string;
  visibility?: string;
  prd: string;
}

export default function IdeaDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);

  const { data, isPending, error } = useQuery({
    queryKey: ["project idea", id],
    queryFn: async () => {
      const token = await getToken();
      return apiClient<{ idea: Idea; related: Idea[] }>(
        `/api/ideas/${id}`,
        { token }
      );
    },
  });

  const [copied, setCopied] = useState(false);

  if (isPending) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <Loader2 className="size-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error || !data?.idea) {
    notFound();
  }

  const { idea, related } = data;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(idea.prd);
      setCopied(true);
      toast.success("Idea copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy idea");
    }
  };

  return (
    <div className="min-h-[60vh] py-12 bg-muted/20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SlideUp>
          <div className="flex items-center justify-between mb-6">
            <Link
              href="/explore/ideas"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="size-4" /> Back to Explore
            </Link>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopy}
              className="gap-2"
            >
              {copied ? <Check className="size-4" /> : <Copy className="size-4" />}
              {copied ? "Copied" : "Copy Idea"}
            </Button>
          </div>
        </SlideUp>

        <SlideUp delay={0.05}>
          <div className="mb-6">
            <h1 className="font-heading scroll-m-20 text-3xl font-bold tracking-tight lg:text-4xl mb-2">
              {idea.projectTitle}
            </h1>
            <p className="text-lg text-muted-foreground font-medium mb-4">
              {idea.tagline}
            </p>
            
            <div className="flex flex-wrap items-center gap-2 mt-4">
              <Badge variant="secondary" className="px-3 py-1 text-xs font-medium">
                <Clock className="size-3 mr-1.5" /> Can be built in {idea.estimatedDuration}
              </Badge>
              <Badge variant="outline" className="px-3 py-1 text-xs font-medium">
                Generated by {idea.ownerName}
              </Badge>
              {idea.visibility === "private" ? (
                <Badge variant="outline" className="px-3 py-1 text-xs font-medium border-amber-500/40 text-amber-600 dark:text-amber-400">
                  <Lock className="size-3 mr-1.5" /> Private
                </Badge>
              ) : (
                <Badge variant="outline" className="px-3 py-1 text-xs font-medium text-muted-foreground">
                  <Globe className="size-3 mr-1.5" /> Public
                </Badge>
              )}
            </div>
          </div>
        </SlideUp>

        <Separator className="my-6" />

        <SlideUp delay={0.1}>
          <Card className="border bg-card shadow-sm">
            <CardContent className="p-6 sm:p-10">
              <div className="prose prose-slate dark:prose-invert max-w-none">
                <ReactMarkdown>{idea.prd || "Generating PRD..."}</ReactMarkdown>
              </div>
            </CardContent>
          </Card>
        </SlideUp>

        {related?.length > 0 && (
          <SlideUp delay={0.35}>
            <div className="mt-12">
              <h2 className="font-heading text-xl font-bold tracking-tight mb-4">
                Related Ideas
              </h2>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {related.map((r) => (
                  <Link key={r._id} href={`/explore/ideas/${r._id}`}>
                    <Card className="h-full hover:shadow-md transition-shadow">
                      <CardContent className="p-5">
                        <h3 className="font-semibold line-clamp-1 mb-1">{r.projectTitle}</h3>
                        <p className="text-sm text-muted-foreground line-clamp-2">{r.elevatorPitch}</p>
                        <div className="flex flex-wrap gap-1 mt-2">
                          {r.techStack?.slice(0, 3).map((t) => (
                            <Badge
                              key={t}
                              variant="outline"
                              className="text-xs"
                            >
                              {t}
                            </Badge>
                          ))}
                        </div>
                      </CardContent>
                    </Card>
                  </Link>
                ))}
              </div>
            </div>
          </SlideUp>
        )}
      </div>
    </div>
  );
}
